package au.sjowl.scripts.xml.translate

/**
 * Created by hello on 16-Aug-18.
 */

object Language {
    val AUTO_DETECT = "auto"
    val AFRIKAANS = "af"
    val ALBANIAN = "sq"
    val ARABIC = "ar"
    val ARMENIAN = "hy"
    val AZERBAIJANI = "az"
    val BASQUE = "eu"
    val BELARUSIAN = "be"
    val BENGALI = "bn"
    val BULGARIAN = "bg"
    val CATALAN = "ca"
    val CHINESE = "zh-CN"
    val CROATIAN = "hr"
    val CZECH = "cs"
    val DANISH = "da"
    val DUTCH = "nl"
    val ENGLISH = "en"
    val ESTONIAN = "et"
    val FILIPINO = "tl"
    val FINNISH = "fi"
    val FRENCH = "fr"
    val GALICIAN = "gl"
    val GEORGIAN = "ka"
    val GERMAN = "de"
    val GREEK = "el"
    val GUJARATI = "gu"
    val HAITIAN_CREOLE = "ht"
    val HEBREW = "iw"
    val HINDI = "hi"
    val HUNGARIAN = "hu"
    val ICELANDIC = "is"
    val INDONESIAN = "id"
    val IRISH = "ga"
    val ITALIAN = "it"
    val JAPANESE = "ja"
    val KANNADA = "kn"
    val KOREAN = "ko"
    val LATIN = "la"
    val LATVIAN = "lv"
    val LITHUANIAN = "lt"
    val MACEDONIAN = "mk"
    val MALAY = "ms"
    val MALTESE = "mt"
    val NORWEGIAN = "no"
    val PERSIAN = "fa"
    val POLISH = "pl"
    val PORTUGUESE = "pt"
    val ROMANIAN = "ro"
    val RUSSIAN = "ru"
    val SERBIAN = "sr"
    val SLOVAK = "sk"
    val SLOVENIAN = "sl"
    val SPANISH = "es"
    val SWAHILI = "sw"
    val SWEDISH = "sv"
    val TAMIL = "ta"
    val TELUGU = "te"
    val THAI = "th"
    val TURKISH = "tr"
    val UKRAINIAN = "uk"
    val URDU = "ur"
    val VIETNAMESE = "vi"
    val WELSH = "cy"
    val YIDDISH = "yi"
    val CHINESE_SIMPLIFIED = "zh-CN"
    val CHINESE_TRADITIONAL = "zh-TW"
}
